tasks:

# Sync updates to files.
  backup:
    priority: 1
    accept_all: yes
    exec:
      on_exit:        
        phase:
          - cd /home/pi/.flexget/ && git pull > /dev/null 2>&1
          - cd /home/pi/.flexget/ && git add * > /dev/null 2>&1
          - cd /home/pi/.flexget/ && git commit -m "update" > /dev/null 2>&1
          - cd /home/pi/.flexget/ && git push origin main > /dev/null 2>&1

# Cleanvid (https://github.com/mmguero/cleanvid) new files.
  clean:
    priority: 2
    filesystem:
      path: "/home/pi/media"
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    exec:
      on_output:
        for_accepted:
          - /usr/local/bin/cleanvid -i "{{location}}" -o "{{location}}_clean.mkv" -w /home/pi/swears.txt -e
          - if [ -f "{{location}}_clean.mkv" ]; then rm "{{location}}"; else echo "nothing to clean"; fi
#      on_exit:
#        phase: find /home/pi/media/ -name "*.srt" -type f -delete > /dev/null 2>&1

# Showrss profile rss
  showrss:
    priority: 3
    rss: https://showrss.info/user/247283.rss?magnets=true&namespaces=true&name=null&quality=anyhd&re=yes
    all_series: yes
    transmission:
      host: 192.168.1.15
      port: 9091
      main_file_only: yes
      username: transmission
      password: transmission
      path: "/data/series"
    exec:
      on_output:
        for_accepted:
          - sed -i '1 i\{{title}}' /home/pi/.flexget/history.txt

# Other series/anime from the series.yml file
  otherrss:
    priority: 3
    include: series.yml
    inputs:
      - rss: { url: 'https://eztv.re/ezrss.xml', silent: yes }
      - rss: { url: 'https://www.limetorrents.info/rss/20/', silent: yes }
      - rss: { url: 'https://torrentgalaxy.to/rss?cat=41', silent: yes }
      - rss: { url: 'https://nyaa.si/?page=rss&q=s0&c=1_2&f=0', silent: yes }
      - rss: { url: 'https://rarbg.to/rssdd.php?category=1;18;41;49', silent: yes }
    transmission:
      host: 192.168.1.15
      port: 9091
      main_file_only: yes
      content_filename: "{{series_name}} - {{series_id}}"
      username: transmission
      password: transmission
      path: "/data/series"
    exec:
      on_output:
        for_accepted:
          - sed -i '1 i\{{title}}' /home/pi/.flexget/history.txt

# Script to import each line of movies.txt
  movie-list:
    priority: 5
    exec:
      on_exit:
        phase:
          - sh /home/pi/.flexget/movies.sh


  download-movies:
    priority: 6
    quality: webrip+
#    magnets: yes
#    convert_magnet:
#      timeout: 10 seconds
#      force: yes
    discover:
      release_estimations: loose
      interval: 15 minutes
      what:
        - movie_list: movies
      from:
        - piratebay:
            category: highres movies
        - limetorrents:
            category: movies
        - rarbg:
            category: [14, 17, 44, 45, 48]
        - yts: true
    list_match:
      from:
        - movie_list: movies
    transmission:
      host: 192.168.1.15
      port: 9091
      main_file_only: yes
      username: transmission
      password: transmission
      path: "/data/movies"
      
  cleanup:
    priority: 10
    delay: 23 hours
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    from_transmission:
      host: 192.168.1.15
      port: 9091
      username: transmission
      password: transmission
    accept_all: yes
    if:
      - transmission_date_done == None: fail
      - not transmission_seed_ratio_ok and not transmission_idle_limit_ok: reject
    transmission:
      host: 192.168.1.15
      port: 9091
      username: transmission
      password: transmission
      action: remove
