tasks:

# Sync updates to files.
  backup:
    priority: 1
    accept_all: yes
    exec:
      on_exit:        
        phase:
          - cd /home/pi/.flexget/ && git pull > /dev/null 2>&1
          - cd /home/pi/.flexget/ && git add config.yml series.yml README.md  > /dev/null 2>&1
          - cd /home/pi/.flexget/ && git commit -m "update" > /dev/null 2>&1
          - cd /home/pi/.flexget/ && git push origin main > /dev/null 2>&1

# Cleanvid (https://github.com/mmguero/cleanvid) new files.
  clean:
    priority: 2
    filesystem:
      path: "/home/pi/series/completed"
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    exec:
      on_output:
        for_accepted:
          - /home/pi/.local/bin/cleanvid -i "{{location}}" -o "{{location}}_clean.mkv" -w /home/pi/swears.txt -e
          - if [ -f "{{location}}_clean.mkv" ]; then rm "{{location}}"; else echo "nothing to clean"; fi

# Showrss profile rss
  rss_shows:
    rss: https://showrss.info/user/247283.rss?magnets=true&namespaces=true&name=null&quality=anyhd&re=yes
    all_series: yes
    transmission:
      host: 192.168.1.15
      port: 9091
      main_file_only: yes
      username: transmission
      password: transmission
      path: "/data/completed/{{series_name}}"
    exec:
      on_output:
        for_accepted:
          - sed -i '1 i\{{title}} <br>' /home/pi/.flexget/README.md

# Other series/anime from the series.yml file
  rss_other:
    include: series.yml
    inputs:
      - rss: https://eztv.re/ezrss.xml
      - rss: https://www.limetorrents.info/rss/20/
      - rss: https://torrentgalaxy.to/rss?cat=41
      - rss: https://rarbg.to/rssdd.php?category=1;18;41;49
      - rss: https://nyaa.si/?page=rss&q=s0&c=1_2&f=0
    transmission:
      host: 192.168.1.15
      port: 9091
      main_file_only: yes
      content_filename: "{{series_name}} - {{series_id}}"
      username: transmission
      password: transmission
      path: "/data/completed/{{series_name}}"
    exec:
      on_output:
        for_accepted:
          - sed -i '1 i\{{title}} <br>' /home/pi/.flexget/README.md

# Remove completed from transmission
  cleanup:
    delay: 23 hours
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    from_transmission:
      host: 192.168.1.15
      port: 9091
      username: transmission
      password: transmission
    accept_all: yes
    if:
      - transmission_date_done == None: fail
      - not transmission_seed_ratio_ok and not transmission_idle_limit_ok: reject
    transmission:
      host: 192.168.1.15
      port: 9091
      username: transmission
      password: transmission
      action: remove

# News RSS generate HTML
  news:
    exec:
      on_output:
        for_accepted:
          - sed -i '1i [{{title}}]({{url}}) <br>' /home/pi/.flexget/README.md
      on_exit:
        phase:
          - echo ### $(date) | cat - /home/pi/.flexget/README.md > temp && mv temp /home/pi/.flexget/README.md
    manual: yes
    disable: seen
    accept_all: yes
    inputs:
    #tech
      - rss: https://github.com/osmoscraft/osmosfeed/releases.atom
      - rss: https://www.reddit.com/r/sysadmin/top.rss?t=week
      - rss: https://www.reddit.com/r/apple/top.rss?t=week
      - rss: https://www.bleepingcomputer.com/feed/
      - rss: https://www.ghacks.net/feed/
      - rss: https://krebsonsecurity.com/feed/
      - rss: https://thesweetsetup.com/feed/
      - rss: https://usesthis.com/feed.atom
    #media
      - rss: https://www.reddit.com/r/television/search.xml?q=flair_name%3A%22Premiere%22&amp;restrict_sr=1&amp;t=week
      - rss: https://www.reddit.com/r/pcgaming/top.rss?t=week
      - rss: https://www.reddit.com/r/steamdeck/top.rss?t=week
      - rss: https://pitchfork.com/rss/reviews/best/albums/
    #news
      - rss: https://www.jw.org/en/news/jw/rss/NewsSubsectionRSSFeed/feed.xml
      - rss: https://feeds.feedburner.com/StudyHacks
    #ytrss
      - rss: https://www.youtube.com/feeds/videos.xml?channel_id=UCE_M8A5yxnLfW0KghEeajjw
      - rss: https://www.youtube.com/feeds/videos.xml?channel_id=UC0k238zFx-Z8xFH0sxCrPJg
