tasks:

# Sync file changes.
  backup:
    priority: 1
    no_entries_ok: yes
    accept_all: yes
    exec:
      on_exit:
        phase:
          - cd /home/ryan/.flexget/ && git pull > /dev/null 2>&1
          - cd /home/ryan/.flexget/ && git add config.yml series.yml getmovies.txt > /dev/null 2>&1
          - cd /home/ryan/.flexget/ && git commit -m "update" > /dev/null 2>&1
          - cd /home/ryan/.flexget/ && git push origin main > /dev/null 2>&1

# Showrss profile rss
  shows-rss:
    priority: 2
    magnets: yes
    convert_magnet:
      timeout: 10 seconds
      force: yes
    rss: https://showrss.info/user/247283.rss?magnets=true&namespaces=true&name=null&quality=anyhd&re=yes
    all_series: yes
    download:
      path: /home/ryan/temp
      overwrite: yes
      fail_html: no
    exec:
      on_output:
        for_accepted:
          - python3 /home/ryan/.flexget/rdadd.py "{{location}}"
          - rm "{{location}}"

# Other series/anime from the series.yml file
  shows-other:
    priority: 3
    include: series.yml
    magnets: yes
    convert_magnet:
      timeout: 10 seconds
      force: yes
    inputs:
      - rss: https://eztv.re/ezrss.xml
      - rss: https://www.limetorrents.info/rss/20/
      - rss: https://torrentgalaxy.to/rss?cat=41
      - rss: https://nyaa.si/?page=rss&q=s01&c=1_2&f=0
    download:
      path: /home/ryan/temp
      overwrite: yes
      fail_html: no
    exec:
      on_output:
        for_accepted:
          - python3 /home/ryan/.flexget/rdadd.py "{{location}}"
          - rm "{{location}}"

# New movies released - trakt list
  movies-new:
    priority: 4
    delay: 12 hours
    imdb_lookup: yes
    trakt_list:
      username: giladg
      list: latest-releases
      type: movies
      strip_dates: yes
    imdb:
      min_score: 7
      min_votes: 5000
      reject_genres:
        - horror
      accept_mpaa_ratings:
        - PG
        - PG-13
    list_add:
      - movie_list: new-movies

  movies-manual:
    priority: 5
    tail:
      file: /home/ryan/.flexget/getmovies.txt
      entry:
        title: '^([^,]+)'
        url: '^([^,]+)'
      encoding: utf8
    accept_all: yes
    list_add:
      - movie_list: new-movies

# Download movies
  movies-get:
    priority: 6
    disable: seen
    tmdb_lookup: yes
    movie_list: new-movies
    quality: 1080p webrip+
    magnets: yes
    convert_magnet:
      timeout: 10 seconds
      force: yes
    content_size:
      min: 1000
      max: 5000
    discover:
      release_estimations: ignore
      interval: 15 minutes
      what:
        - movie_list: new-movies
      from:
        - piratebay:
            category: highres movies
        - limetorrents:
            category: movies
        - yts: true
    list_match:
      from:
        - movie_list: new-movies
    download:
      path: /home/ryan/temp
      overwrite: yes
      fail_html: no
    exec:
      on_output:
        for_accepted:
          - python3 /home/ryan/.flexget/rdadd.py "{{location}}"
          - rm "{{location}}"

# Cleanvid (https://github.com/mmguero/cleanvid) new files.
  clean-shows:
    priority: 7
    metainfo_series: yes
    trakt_lookup: yes
    tvmaze_lookup: yes
    filesystem:
      path: "/home/ryan/torrents/shows"
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    if:
      - trakt_series_content_rating == 'TV-MA': accept
      - "'anime' in trakt_genres": reject
    exec:
      on_start:
        phase: sleep 30
      on_output:
        for_accepted:
          - cp "{{location}}" /mnt/d/Media/"{{filename}}"
          - /home/ryan/.local/bin/cleanvid -i /mnt/d/Media/"{{filename}}" -o /mnt/d/Media/"{{filename}}_clean.mkv" -w /home/ryan/.flexget/swears.txt -e -p 0
          - if [ -f /mnt/d/Media/"{{filename}}_clean.mkv" ]; then rm /mnt/d/Media/"{{filename}}"; else echo "nothing to clean"; fi
          - rm "{{location}}"
      on_exit:
        phase: rm /mnt/d/Media/*.srt
