tasks:

##
  backup:
    priority: 1
    accept_all: yes
    exec:
      on_exit:        
        phase:
          - cd /home/ryan/.flexget/ && git pull > /dev/null 2>&1
          - cd /home/ryan/.flexget/ && git add * > /dev/null 2>&1
          - cd /home/ryan/.flexget/ && git commit -m "update" > /dev/null 2>&1
          - cd /home/ryan/.flexget/ && git push origin main > /dev/null 2>&1

  move:
    priority: 2
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    metainfo_series: yes
    parsing:
      series: guessit
    tvmaze_lookup: yes
    filesystem:
      path: "/home/ryan/completed"
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    move:
      to: "/home/ryan/media"
      rename: "{{series_name|escape|replace('&#39;', '')|pathscrub}} - {{series_id}}"
      clean_source: 50
    exec:
      on_output:
        for_accepted:
          - /usr/local/bin/cleanvid -i "{{location}}" -o "{{location}}_clean.mkv" -w /home/ryan/swears.txt -e > /dev/null 2>&1
          - if [ -f "{{location}}_clean.mkv" ]; then rm "{{location}}"; else echo "nothing to clean"; fi > /dev/null 2>&1
          - echo {{title}} >> /home/ryan/.flexget/history.txt
      on_exit:
        phase: find "/home/ryan/completed/"* -type d -empty -delete       

##
  rss:
    priority: 3
    tvmaze_lookup: yes
    include: series.yml
    content_filter:
      require:
        - '*.mkv'
        - '*.mp4'
    domain_delay:
      nyaa: 3 seconds
      limetorrents: 3 seconds
      thepiratebay.se: 10 seconds
      thepiratebay.org: 10 seconds
      anidex.info: 3 seconds
      bt-chat.com: 1 seconds
      ezrss.it: 1 seconds
      showrss.info: 2 seconds
      torlock.eu: 1 seconds
      torrenticity.com: 1 seconds
      zooqle.com: 2 seconds
    inputs:
      - rss: { url: 'https://eztv.re/ezrss.xml', silent: yes }
      - rss: { url: 'https://eztv.it/ezrss.xml', other_fields: ['torrent:magnetURI'], link: 'torrent:magnetURI', silent: yes }
      - rss: { url: 'https://www.limetorrents.info/rss/20/', silent: yes }
      - rss: { url: 'https://torrentgalaxy.to/rss?cat=41', silent: yes }
      - rss: { url: 'https://nyaa.si/?page=rss&c=1_2', silent: yes }
      - rss: { url: 'https://rarbg.to/rssdd.php?category=1;18;41;49', silent: yes }
      - rss: 
          url: https://zooqle.com/search?q=%2A+category%3ATV&fmt=rss
          title: 'torrent:fileName'      
    transmission:
      host: 192.168.1.15
      port: 9091
      main_file_only: yes
      username: transmission
      password: transmission
      path: "/data/completed/{{series_name}}"
      content_filename: "{{series_name|escape|replace('&#39;', '')|pathscrub}} - {{series_id}}"

##
  search:
    priority: 4
    delay: 2 hours
    tvmaze_lookup: yes
    include: series.yml
    content_filter:
      require:
        - '*.mkv'
        - '*.mp4'
    domain_delay:
      nyaa: 3 seconds
      limetorrents: 3 seconds
    discover:
      release_estimations: strict
      interval: 15 minutes
      what:
        - next_series_episodes: yes
      from:
        - piratebay:
            category: highres tv
        - limetorrents:
            category: tv
        - rarbg:
            category: [2, 18, 41, 49]
        - nyaa:
            category: anime eng
            filter: all
        - search_rss: https://torrentz2.eu/feed?f=\{{search_term}}
    transmission:
      host: 192.168.1.15
      port: 9091
      main_file_only: yes
      username: transmission
      password: transmission
      path: "/data/completed/{{series_name}}"
      content_filename: "{{series_name|escape|replace('&#39;', '')|pathscrub}} - {{series_id}}"

##
  cleanup:
    priority: 5
    delay: 3 days
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    from_transmission:
      host: 192.168.1.15
      port: 9091
      username: transmission
      password: transmission
    accept_all: yes
    if:
      - transmission_date_done == None: fail
      - not transmission_seed_ratio_ok and not transmission_idle_limit_ok: reject
    transmission:
      host: 192.168.1.15
      port: 9091
      username: transmission
      password: transmission
      action: remove
    exec:
      on_exit:
        phase: find /home/ryan/media/ -name "*.srt" -type f -delete > /dev/null 2>&1

  test:
    priority: 3
    manual: yes
    include: series.yml
    accept_all: yes
    list_add:
      - trakt_list:
          account: thetinyking
          list: series
          type: shows
