tasks:

  clean:
    priority: 1
    filesystem:
      path: "/home/ryan/media"
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    exec:
      on_output:
        for_accepted:
          - /usr/local/bin/cleanvid -i "{{location}}" -o "{{location}}_clean.mkv" -w /home/ryan/swears.txt -e
          - if [ -f "{{location}}_clean.mkv" ]; then rm "{{location}}"; else echo "nothing to clean"; fi

  showrss:
    priority: 2
    rss: https://showrss.info/user/247283.rss?magnets=true&namespaces=true&name=null&quality=anyhd&re=yes
    all_series: yes
    transmission:
      host: 192.168.1.15
      port: 9091
      main_file_only: yes
      username: transmission
      password: transmission
      path: "/data/media/"

  otherrss:
    priority: 3
    include: series.yml
    inputs:
      - rss: { url: 'https://eztv.re/ezrss.xml', silent: yes }
      - rss: { url: 'https://eztv.it/ezrss.xml', other_fields: ['torrent:magnetURI'], link: 'torrent:magnetURI', silent: yes }
      - rss: { url: 'https://www.limetorrents.info/rss/20/', silent: yes }
      - rss: { url: 'https://torrentgalaxy.to/rss?cat=41', silent: yes }
      - rss: { url: 'https://nyaa.si/?page=rss&c=1_2', silent: yes }
      - rss: { url: 'https://rarbg.to/rssdd.php?category=1;18;41;49', silent: yes }
    transmission:
      host: 192.168.1.15
      port: 9091
      main_file_only: yes
      username: transmission
      password: transmission
      path: "/data/media/"

  cleanup:
    priority: 5
    delay: 3 days
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    from_transmission:
      host: 192.168.1.15
      port: 9091
      username: transmission
      password: transmission
    accept_all: yes
    if:
      - transmission_date_done == None: fail
      - not transmission_seed_ratio_ok and not transmission_idle_limit_ok: reject
    transmission:
      host: 192.168.1.15
      port: 9091
      username: transmission
      password: transmission
      action: remove
    exec:
      on_exit:
        phase: find /home/ryan/media/ -name "*.srt" -type f -delete > /dev/null 2>&1
