tasks:

# Sync updates to files.
  backup:
    priority: 1
    accept_all: yes
    exec:
      on_exit:        
        phase:
          - cd 'c:\Users\ryan\flexget' & git pull
          - cd 'c:\Users\ryan\flexget' & git add *
          - cd 'c:\Users\ryan\flexget' & git commit -m "update"
          - cd 'c:\Users\ryan\flexget' & git push origin main

# Cleanvid (https://github.com/mmguero/cleanvid) new files.
  moveSeries:
    priority: 2
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    metainfo_series: yes
    tvmaze_lookup: yes
    parsing:
      series: guessit
    filesystem:
      path: 'd:\Download'
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    move:
      to: 'd:\Series\{{series_name}}'
      rename: "{{series_name|escape|replace('&#39;', '')|pathscrub}} - {{series_id}}{% if tvmaze_episode_name|default(False) %} - {{tvmaze_episode_name|pathscrub}}{% endif %}{% if quality|default(False) %} - [{{quality}}]{% endif %}"
    accept_all: yes
    exec:
      on_output:
        for_accepted:
          - cleanvid -i "{{location}}" -o "{{location}}_clean.mkv" -w 'd:\Scripts\swears.txt' -e
          - if [ -f "{{location}}_clean.mkv" ]; then rm "{{location}}"; else echo "nothing to clean"; fi

# Showrss profile rss
  showrss:
    priority: 3
    rss: https://showrss.info/user/247283.rss?magnets=true&namespaces=true&name=null&quality=anyhd&re=yes
    all_series: yes
    qbittorrent: 
      path: 'd:\Download\series\{{series_name}}'

# Other series/anime from the series.yml file
  otherrss:
    priority: 3
    include: series.yml
    inputs:
      - rss: { url: 'https://eztv.re/ezrss.xml', silent: yes }
      - rss: { url: 'https://www.limetorrents.info/rss/20/', silent: yes }
      - rss: { url: 'https://torrentgalaxy.to/rss?cat=41', silent: yes }
      - rss: { url: 'https://nyaa.si/?page=rss&q=s0&c=1_2&f=0', silent: yes }
      - rss: { url: 'https://rarbg.to/rssdd.php?category=1;18;41;49', silent: yes }
    qbittorrent: 
      path: 'd:\Download\series\{{series_name}}'
