tasks:

# Cleanvid (https://github.com/mmguero/cleanvid) new files.
  clean:
    priority: 1
    metainfo_series: yes
    trakt_lookup: yes
    tvmaze_lookup: yes
    filesystem:
      path: "/home/pi/downloads/complete"
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    if:
      - trakt_series_content_rating == 'TV-MA': accept
      - "'anime' in trakt_genres": reject
    exec:
      on_output:
        for_accepted:
          - /home/pi/.local/bin/cleanvid -i "{{location}}" -o "{{location}}_clean.mkv" -w /home/pi/flexget/swears.txt -e
          - if [ -f "{{location}}_clean.mkv" ]; then rm "{{location}}"; else echo "nothing to clean"; fi
          - find "{{location}}"*.srt -type f -delete

# Showrss profile rss
  showrss:
    priority: 2
    rss: https://showrss.info/user/247283.rss?magnets=true&namespaces=true&name=null&quality=anyhd&re=yes
    all_series: yes
    transmission:
      host: 192.168.0.53
      port: 9091
      main_file_only: yes
      username: transmission
      password: transmission
      path: "/downloads/complete/{{series_name}}"

# Other series/anime from the series.yml file
  other:
    priority: 3
    include: series.yml
    inputs:
      - rss: https://eztv.re/ezrss.xml
      - rss: https://www.limetorrents.info/rss/20/
      - rss: https://torrentgalaxy.to/rss?cat=41
      - rss: https://rarbg.to/rssdd.php?category=1;18;41;49
      - rss: https://nyaa.si/?page=rss&q=s01&c=1_2&f=0
    transmission:
      host: 192.168.0.53
      port: 9091
      main_file_only: yes
      content_filename: "{{series_name}} - {{series_id}}"
      username: transmission
      password: transmission
      path: "/downloads/complete/{{series_name}}"

# Remove complete from transmission
  cleanup:
    priority: 4
    delay: 23 hours
    no_entries_ok: yes
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    from_transmission:
      host: 192.168.0.53
      port: 9091
      username: transmission
      password: transmission
    accept_all: yes
    if:
      - transmission_date_done == None: fail
      - not transmission_seed_ratio_ok and not transmission_idle_limit_ok: reject
    transmission:
      host: 192.168.0.53
      port: 9091
      username: transmission
      password: transmission
      action: remove

# Sync updates to files.
  backup:
    priority: 5
    no_entries_ok: yes
    accept_all: yes
    exec:
      on_exit:
        phase:
          - cd /home/pi/.flexget/ && git pull > /dev/null 2>&1
          - cd /home/pi/.flexget/ && git add config.yml series.yml > /dev/null 2>&1
          - cd /home/pi/.flexget/ && git commit -m "update" > /dev/null 2>&1
          - cd /home/pi/.flexget/ && git push origin main > /dev/null 2>&1
