tasks:

# Sync updates to files.
  backup:
    priority: 1
    accept_all: yes
    exec:
      on_exit:        
        phase:
          - cd /home/pi/.flexget/ && git pull > /dev/null 2>&1
          - cd /home/pi/.flexget/ && git add config.yml series.yml history.log > /dev/null 2>&1
          - cd /home/pi/.flexget/ && git commit -m "update" > /dev/null 2>&1
          - cd /home/pi/.flexget/ && git push origin main > /dev/null 2>&1

# Cleanvid (https://github.com/mmguero/cleanvid) new files.
  clean:
    priority: 2
    filesystem:
      path: "/home/pi/series"
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    exec:
      on_output:
        for_accepted:
          - /home/pi/.local/bin/cleanvid -i "{{location}}" -o "{{location}}_clean.mkv" -w /home/pi/swears.txt -e
          - if [ -f "{{location}}_clean.mkv" ]; then rm "{{location}}"; else echo "nothing to clean"; fi
      on_exit:
        phase: find /home/pi/series/ -name "*.srt" -type f -delete > /dev/null 2>&1

# Showrss profile rss
  rss_shows:
    rss: https://showrss.info/user/247283.rss?magnets=true&namespaces=true&name=null&quality=anyhd&re=yes
    all_series: yes
    transmission:
      host: 192.168.1.15
      port: 9091
      main_file_only: yes
      username: transmission
      password: transmission
      path: "/data/series/{{series_name}}"
    exec:
      on_output:
        for_accepted:
          - sed -i '1i {{title}}' /home/pi/.flexget/history.log

# Other series/anime from the series.yml file
  rss_other:
    include: series.yml
    inputs:
      - rss: https://eztv.re/ezrss.xml
      - rss: https://www.limetorrents.info/rss/20/
      - rss: https://torrentgalaxy.to/rss?cat=41
      - rss: https://rarbg.to/rssdd.php?category=1;18;41;49
      - rss: https://nyaa.si/?page=rss&q=s0&c=1_2&f=0
    transmission:
      host: 192.168.1.15
      port: 9091
      main_file_only: yes
      content_filename: "{{series_name}} - {{series_id}}"
      username: transmission
      password: transmission
      path: "/data/series/{{series_name}}"
    exec:
      on_output:
        for_accepted:
          - sed -i '1i {{title}}' /home/pi/.flexget/history.log

##### Search for episodes
  show_search:
    delay: 6 hours
    include: series.yml
    discover:
      release_estimations: ignore
      interval: 5 minutes
      what:
        - next_series_episodes: yes
      from:
        - piratebay:
            category: highres tv
        - limetorrents:
            category: tv
        - rarbg:
            category: [2, 18, 41, 49]
        - nyaa:
            category: anime eng
            filter: all
    transmission:
      host: 192.168.1.15
      port: 9091
      main_file_only: yes
      content_filename: "{{series_name}} - {{series_id}}"
      username: transmission
      password: transmission
      path: "/data/series/{{series_name}}"
    exec:
      on_output:
        for_accepted:
          - sed -i '1i {{title}}' /home/pi/.flexget/history.log

# Remove completed from transmission
  cleanup:
    delay: 23 hours
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    from_transmission:
      host: 192.168.1.15
      port: 9091
      username: transmission
      password: transmission
    accept_all: yes
    if:
      - transmission_date_done == None: fail
      - not transmission_seed_ratio_ok and not transmission_idle_limit_ok: reject
    transmission:
      host: 192.168.1.15
      port: 9091
      username: transmission
      password: transmission
      action: remove
