tasks:

  clean:
    filesystem:
      path: "/home/ryan/media"
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    exec:
      on_output:
        for_accepted:
          - /usr/local/bin/cleanvid -i "{{location}}" -o "{{location}}_clean.mkv" -w /home/ryan/swears.txt -e
          - if [ -f "{{location}}_clean.mkv" ]; then rm "{{location}}"; else echo "nothing to clean"; fi
      on_exit:
        phase: find /home/ryan/media/ -name "*.srt" -type f -delete
        
  series:
    priority: 2
    template:
      - series
      - torrent
    inputs:
      - rss: { url: 'https://eztv.re/ezrss.xml', silent: yes }
      - rss: { url: 'https://www.limetorrents.info/rss/20/', silent: yes }
      - rss: { url: 'https://torrentgalaxy.to/rss?cat=41', silent: yes }
#      - rss: { url: 'http://www.torlock.com/movies/rss.xml', silent: yes }
      - rss: { url: 'https://nyaa.si/?page=rss&c=1_2', silent: yes }

  series-search:
    priority: 3
    template:
      - series
      - torrent
    discover:
      release_estimations: strict
      interval: 15 minutes
      what:
        - next_series_episodes: yes
      from:
        - piratebay:
            category: highres tv
        - limetorrents:
            category: tv
        - rarbg:
            category: [2, 18, 41, 49]
        - nyaa:
            category: anime eng
            filter: all
            
  backup:
    accept_all: yes
    exec:
      on_exit:        
        phase:
          #github
          - cd /home/ryan/.flexget/ && git pull
          - cd /home/ryan/.flexget/ && git add *
          - cd /home/ryan/.flexget/ && git commit -m "update"
          - cd /home/ryan/.flexget/ && git push origin main

##########################

templates:

  series:
    tvmaze_lookup: yes
    include: series.yml
    content_filter:
      require:
        - '*.mkv'
        - '*.mp4'
    domain_delay:
      nyaa: 3 seconds
      limetorrents: 3 seconds
  
  torrent:
    transmission:
      host: 192.168.1.15
      port: 9091
      main_file_only: yes
      username: transmission
      password: transmission
      path: "/data/media/{{series_name}}"
      content_filename: "{{series_name}}-{{series_id}}"
      
  global:
    no_entries_ok: yes
    pathscrub: windows
    log_filter:
    - message: "is already marked seen in the task populate-series-db"
    - message: "is before begin value"
    - message: "because entity has already been downloaded"
    - message: "because quality already downloaded"
    - message: "appears to be an episode pack"
      plugin: parser_internal
    - message: "rejecting"
      plugin: content_size
    - message: "Field `title` is now "
      plugin: manipulate

schedules:
  - tasks: ['series']
    schedule:
      minute: 0,30
  - tasks: ['clean', 'backup']   
    schedule:
      hour: 0
  - tasks: ['series-search']
    schedule:
      hour: '*/2'
