variables: secrets.yml
tasks:

# Sync file changes.
  backup:
    manual: yes
    priority: 1
    no_entries_ok: yes
    accept_all: yes
    exec:
      on_exit:
        phase:
          - cd /home/ryan/.flexget/ && git pull > /dev/null 2>&1
          - cd /home/ryan/.flexget/ && git add config.yml > /dev/null 2>&1
          - cd /home/ryan/.flexget/ && git commit -m "update" > /dev/null 2>&1
          - cd /home/ryan/.flexget/ && git push origin main > /dev/null 2>&1

# PlexDebrid.
  plexdebrid:
    priority: 2
    no_entries_ok: yes
    accept_all: yes
    exec:
      on_start:
        phase:
          - cd /home/ryan/plex_debrid/ && screen -d -m python3 main.py
          - echo "wait 10 min..."
          - sleep 600
      on_exit:
        phase:
          - pkill screen

# Any files on RD pending add
  rdsync:
    priority: 3
    no_entries_ok: yes
    accept_all: yes
    exec:
      on_exit:
        phase:
          - python3 /home/ryan/.flexget/rdadd.py
